const mongoose = require('mongoose');
const CompraSchema = mongoose.Schema({
    proveedor:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Proveedor"
    },
    sucursal:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Sucursal"
    },
    usuario_pre_compra:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Usuario"
    },
    usuario_confirmacion:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Usuario"
    },
    tipo_usuario_confirmacion:{
        type:String
    },
    nro_comprobante:{
        type:String
    },
    fecha_pre_compra_movimiento:{
        type:Date
    },
    fecha_pre_compra_sistema:{
        type:Date
    },
    fecha_confirmacion_movimiento:{
        type:Date
    },
    fecha_confirmacion_sistema:{
        type:Date
    },
    costo_total:{
        type:Number,
        default:0.0
    },
    pre_compra_terminada:{
        type:Boolean,
        default:false
    },
    confirmado:{
        type:Boolean,
        default:false
    },
    observaciones_pre_compra:{
        type:String
    },
    observaciones_confirmacion:{
        type:String
    },
    compra_productos:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"CompraProducto"
    }]
});
module.exports = mongoose.model('Compra',CompraSchema);